### ISSUE TITLE
Can't build wasm

### ISSUE THREAD

**Issue by jrowny** [relgin/cardspotter#5]
Tried to build the WASM file following the instructions but got a bunch of errors like:`canny.cpp.o: machine type must be wasm32` from the OpenCV lib included in the download.

So I tried to build opencv @ 4.0.1 with emscripten and it almost works except I can't get it to output the imgcodecs.a file. 

Was just trying to do a build with exception catching so I can see why I've got a problem using the wasm directly in a project I'm working on.

Thanks for this project btw, it's great!

**Comment by relgin** [comment]
Hi Jonathan,
Thank you for the kind words :)

I always try to reproduce bugs with CSTest as an executable as I feel it
gives me much better debug tools (Visual Studio in my case). Any chance you
could do that?

Not sure about your compile issue, it has been a good while since i built
opencv. I'm also unfamiliar with the wasm32 issue as well but I can give
them a try this weekend.

Cheers
Jonas

**Comment by jrowny** [comment]
The bug i'm running into is WASM finishing loading the magic.db database in the browser, so  I don't think CSTest will help there.

It's weird because it loads fine in the extension and it loads fine on my PC when run locally, but on my mac and when deployed, there's an exception after the XHR from emscripten_fetch returns. I'm thinking maybe it's getting the wrong charset or something, but I can't see the actual exception.

But I'd love to be able to build so I could make a more modularized version of the wasm. My use case is that I'm building a peer-to-peer webcam app where we can play magic using our webcams and click on each other's feeds. Cardspotter only works on the first video it sees, so I'm having to merge all the video streams together and that's a bit intense and limits layout possibilities.

Thanks for your reply!

**Comment by relgin** [comment]
Very cool! Love to see something more come of this. When you say all do you
mean more than one opponent then I guess?

A more modular version is something that I've wanted to do but I have very
little time nowadays (which is why I spent some this summer to make it open
source).

How do you mean deployed? Not sure I understand the setup. Wasm loaded
directly from a webpage (with multiple webcams?). Should be able to
replicate the mouse grab (after some js code cleanup) and send it to the
wasm for detection. And you might be able to modify the extension to work
on that part until you've figured out that annoying bug?

Now about your issue(s). Have you tried an empty file? (Not sure it works
on any version but feels like it should)

Not outputting the img*.a sounds like a config thing but I'm not sure what
it would be. I know I had issues with PNG defines at some point but that
just meant it failed to load images.

Cheers
Jonas Gillberg

**Comment by jrowny** [comment]
So I finally got it to build. I couldn't get opencv 4.0.1 building so I just buit from opencv master. Here's what I had to do:

- Use latest emscripten
- Use latest (master) opencv
- Modify platforms/js/build_js.py in opencv to change `DBUILD_opencv_imgcodecs=ON`
- run ` python ./platforms/js/build_js.py build_wasm --build_wasm --emscripten_dir ../emsdk/upstream/emscripten` (or wherever you put your emsdk)
- *this is the part I was missing*, cd into `build_wasm` and run `make`
- modify buildwasm.sh in cardspotter so that `OPENCV=` points to your opencv directory
- modify buildwasm.sh to include `-I$OPENCV/modules/flann/include/` and `$OPENCV/build_wasm/lib/libopencv_flann.a` because I guess they moved to their own modules now

finally, `buildwasm.sh` should run just fine. Haven't' actually tested the build yet, just wanted to write that down before I forgot it and in case anyone else runs into trouble building.

**Comment by jrowny** [comment]
Well, after enabling debugging I figured out the actual issue, the generated magic.db file has CRLF line endings, but OSX uses LF line endings. I guess I don't understand why it works in the extension, maybe the extension distribution process auto-converts the file, but git preserves it. 

Anyway, I got it working now with LF endings, but in general, I think it might be safer to switch the magic.db to magic.json. 

I'll close this issue for now. Let me know if you want a PR with a debug build option and latest openCV instructions.

**Comment by relgin** [comment]
Of course! >< and fantastic that you got both things to work. A PR would be
great -debug support sounds quite helpful :)

Cheers
Jonas

**Comment by relgin** [comment]
Hi Jonathan, how is it going?

If there is anything I can do to help please let me know. Also, I'd
appreciate anything you can share in whichever way is most convenient for
you - no need for a polished PR.

Cheers
Jonas

**Comment by relgin** [comment]
Hi Jonathan!

Could you share the work you did to add multivideo support? It would
really help people set up remote EDH sessions.

(if not I will start working on it tonight and I would much rather base
anything I do on your work)

Cheers
Jonas

**Comment by jrowny** [comment]
I just posted a PR, the changes don't help the extension as much, unfortunately, they just make it more modular so other software can incorporate it by passing any image data in an easy to use way.
